package ProjEuProblems;

import ProjEuUtil.Util;

public class Problem45 implements Problem{

	/*
	 * Triangle, pentagonal, and hexagonal numbers are generated by the
	 * following formulae:
	 * 
	 * Triangle Tn=n(n+1)/2 1, 3, 6, 10, 15, ...
	 * 
	 * Pentagonal Pn=n(3n-1)/2 1, 5, 12, 22, 35, ...
	 * 
	 * Hexagonal Hn=n(2n-1) 1, 6, 15, 28, 45, ... 
	 * 
	 * It can be verified that T285 =
	 * P165 = H143 = 40755.
	 * 
	 * Find the next triangle number that is also pentagonal and hexagonal.
	 */

	public static void main(String[] args) {
		
		//for (int i = 1; i < 22; i++) {
		//	System.out.println("Tri num " + i + " = " + Util.getNthTriangleNumber(i));
		//	System.out.println("pent num " + i + " = " + Util.getNthPentagonalNumber(i));
		//	System.out.println("hex num " + i + " = " + Util.getNthHexagonalNumber(i) + "\n");
		//}
		
		Problem p = new Problem45();
		p.runProblem();
	}

	public String problem() {
		int start = 40755 + 1;
		long max = 100000000000L;
		for (long i = start; i < max; i++) {
			long tri = Util.getNthTriangleNumber(i);
			if (Util.isPentagonalNumber(tri) && Util.isHexagonalNumber(tri)) {
				System.out.println("Found one that is all 3 : " + tri);
				System.out.println("for i=" + i + " Triangle:" + Util.getIndexOfTriangleNumber(tri) + " Pentagonal:"
						+ Util.getIndexOfPentagonalNumber(tri) + " Hexagonal:" + Util.getIndexOfHexagonal(tri));
				
				return "" + tri;
			}
		}
		
		return null;

	}

}
