
public class Problem2 extends ProblemImpl { //Took 0.000200 seconds
	
	/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

		By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
	
	
	public static void main(String[] args){
		Problem p = new Problem2();
		p.runProblem();
	}

	@Override
	public void problem(){
		int total = 0;
		int val1 = 1, val2 = 2;
		
		int max = 4000000;
		while (true){
			
			if(val2 % 2 == 0){
				total += val2;
			}
			int newVal = val1 + val2;
			val1 = val2;
			val2 = newVal;
			
			if(val2 > max){
				break;
			}
			
			
		}
		System.out.println("Val1 : " + val1 + ", val2 : " + val2);
		System.out.println("Answer : " + total);
	}
	
}
