
public class Problem45 {

	/*
	 * Triangle, pentagonal, and hexagonal numbers are generated by the
	 * following formulae:
	 * 
	 * Triangle Tn=n(n+1)/2 1, 3, 6, 10, 15, ...
	 * 
	 * Pentagonal Pn=n(3n-1)/2 1, 5, 12, 22, 35, ...
	 * 
	 * Hexagonal Hn=n(2n-1) 1, 6, 15, 28, 45, ... 
	 * 
	 * It can be verified that T285 =
	 * P165 = H143 = 40755.
	 * 
	 * Find the next triangle number that is also pentagonal and hexagonal.
	 */

	public static void main(String[] args) {
		problem();
	}

	private static void problem() {
		int start = 40755 + 1;
		long max = 100000000000L;
		for (long i = start; i < max; i++) {
			if (Util.isTriangleNumber(i) && Util.isPentagonalNumber(i) && Util.isHexagonalNumber(i)) {
				System.out.println("Found one that is all 3 : " + i);
				System.out.println("for i=" + i + " Triangle:" + Util.getIndexOfTriangleNumber(i) + " Pentagonal:"
						+ Util.getIndexOfPentagonalNumber(i) + " Hexagonal:" + Util.getIndexOfHexagonal(i));
				return;
			}
		}

	}

}
